reworked log transformer tests
lvgig/tubular pull request #268
Opened 2024-07-05 14:32 UTC by limlam96

moved tests for LogTransformer to new setup

2024-07-10 15:44 UTC, davidhopkinson26 approved these changes
Happy with this, thanks!

2024-07-10 15:44 UTC, davidhopkinson26 requested changes
Update changelog please

2024-07-15 08:37 UTC, limlam96 commented
updated changelog here https://github.com/lvgig/tubular/pull/268/commits/a198103e0120832f4941060cce042e3c40558102

2024-07-15 09:36 UTC, davidhopkinson26 approved these changes

2024-07-15 09:36 UTC, merged