Sphinxify api
lvgig/tubular pull request #3
Opened 2021-05-08 14:30 UTC by munichpavel

Closes #2 

Add sphinx doc files for local build of api documentation

Changes to the standard quickstart-generated files are

* Put Sphinx build directory in an environment variable (see .envrc.example)
* Add api autodoc generated files in docs/source/api
* Use rtd theme
* Add documentation build instructions to README
* Remove link to not-yet-existent read-the-docs page

2021-05-19 09:32 UTC, richardangell requested changes
hi - can you remove the `.rst` files for `modules`, `tubular`, `tubular.testing` and `tubular.testing.test_data` please? there's quite a lot of duplication in the links and `testing.test_data` it quite messy so doesn't need to be exposed through the docs right now. Thanks!

2021-05-20 12:59 UTC, munichpavel commented
Thanks, @richardangell! Sure, will do.

2021-05-28 04:28 UTC, munichpavel commented
Hi @richardangell ! Please let me know if the changes made are what you had in mind. I also rebased this forked branch to hopefully make the commit history order consistent with master. If this is not the case, I'll try to undo my fix :).

2021-06-01 12:08 UTC, richardangell approved these changes

2021-06-01 12:09 UTC, merged