Feature/refactor datediff tests
lvgig/tubular pull request #307
Opened 2024-09-23 12:35 UTC by limlam96

testing refactor https://github.com/lvgig/tubular/issues/296

2024-09-24 08:42 UTC, davidhopkinson26 requested changes
Happy with these changes.  Again, sacrificing the automatic new column naming ok for now.  I think this justifies the next version bump being to 1.4.0 though a sit is a breaking change.  Please update the Changelog to reflect.

2024-10-04 12:19 UTC, limlam96 commented
updated changelog here https://github.com/lvgig/tubular/pull/307/commits/b6bf059c9acab5de9c490d167fe8334b41d5b03a

2024-10-04 12:22 UTC, limlam96 commented
oops, and here https://github.com/lvgig/tubular/pull/307/commits/db08c0c9ac21d663b2b81bc671f272745a2f65ac

2024-10-07 08:32 UTC, davidhopkinson26 approved these changes

2024-10-07 08:32 UTC, merged