converted basenominaltransformer to polars
lvgig/tubular pull request #335
Opened 2024-10-17 10:46 UTC by limlam96

https://github.com/lvgig/tubular/issues/334

2024-11-06 15:54 UTC, davidhopkinson26 requested changes
think we also need to edit inverse_transform.  It has a replace operation in there.

2024-11-06 16:10 UTC, davidhopkinson26 commented on tests/nominal/test_BaseNominalTransformer.py
> +        transformer = initialized_transformers[self.transformer_name]
P: thanks for changing from x -> transformer!

2024-11-07 11:20 UTC, limlam96 commented
> think we also need to edit inverse_transform. It has a replace operation in there.

inverse_transform is in 'NominalToIntegerTransformer' so was leaving for that issue? unless i'm mixed up!

2024-11-07 13:49 UTC, davidhopkinson26 commented
> > think we also need to edit inverse_transform. It has a replace operation in there.
> 
> inverse_transform is in 'NominalToIntegerTransformer' so was leaving for that issue? unless i'm mixed up!

My bad sorry!

2024-11-07 13:50 UTC, davidhopkinson26 approved these changes

2024-11-07 13:50 UTC, merged